language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -u root -e "create user 'root'@'localhost' identified by 'root'"
  - mysql -u root -e "grant all privileges on belajarci.* to 'root'@'localhost' with grant option"
  - mysql -u root -e "drop database if exists belajarci"
  - mysql -u root -e "create database belajarci"
  - chmod +x mvnw