language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -u root -e "create user 'user'@'localhost' identified by 'user'"
  - mysql -u root -e "drop database if exists belajarci"
  - mysql -u root -e "create database belajarci"
  - mysql -u root -e "grant all privileges on belajarci.* to 'user'@'localhost'"
  - chmod +x mvnw